sudo: required
dist: trusty
language: C++
compiler:
  - clang
install:
  - sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" -y
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -y
  - sudo apt-get install clang-3.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
script:
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi
  - cmake -G "Unix Makefiles"
  - make -j $[$(grep -c ^processor /proc/cpuinfo)2]
