sudo: required
dist: trusty
language: C++
compiler:
  - clang
install:
  - sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" -y
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -y
  - sudo apt-get install clang-3.9
  - ls /usr/bin
  - sudo rm /usr/bin/clang && sudo ln -s /usr/bin/clang-3.9 /usr/bin/clang
  - sudo rm /usr/bin/clang++ && sudo ln -s /usr/bin/clang++-3.9 /usr/bin/clang++-3.9
script:
  - cmake -G "Unix Makefiles"
  - make -j $[$(grep -c ^processor /proc/cpuinfo)2]
