sudo: required
dist: trusty
language: C++
compiler:
  - clang
install:
  - sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" -y
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -y
  - sudo apt-get install clang-3.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
script:
  - if [ "$CXX" = "clang++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - cmake -G "Unix Makefiles" -DCLANG_WITH_LIB_STD_CPP=true
  - make -j $[$(grep -c ^processor /proc/cpuinfo)2]
